services:
  dev:
    build: .
    image: php8.4-cli
    container_name: php8.4-laravel-cli-dev
    command: bash -c "composer install && /bin/bash"
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./php.ini-development
        target: /usr/local/etc/php/php.ini
    ports:
      - "8123:8123"
