services:
  dev:
    build: .
    image: php8.3-cli
    container_name: php8.3-cli-debug
    command: bash -c "/bin/bash"
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    tty: true
    volumes:
      - .:/app
    ports:
      - "8123:8123"
